Moves date stamp banner for URN flow to confirm details page
ministryofjustice/laa-crime-apply-prototype pull request #98
Opened 2022-05-09 17:14 UTC by arthurashman

2022-05-10 16:24 UTC, arthurashman commented
I think I need to talk through the logic of the datestamp to make sure the right users are seeing it - there's a lot going on in the POST ioj route that I think this PR may circumnavigate

2022-05-11 15:44 UTC, oliverweighell requested changes

2022-05-11 15:44 UTC, oliverweighell commented on app/routes.js
> -  res.render('application_cert_review', { date_of_birth: utils.formatDate(date), date_stamp: passported });
Looks like we're moving the date stamp forward (to case_details_offence) in the MVP journey? Will this still work where the user goes down case_details_urn path? (ie will the user see the date stamp banner on that journey?)

2022-05-11 15:44 UTC, oliverweighell commented on app/views/case_details_offence.html
> +  {% endif %}
We could move the date stamp snippet into an 'include' that can then be called into the various pages it's needed? Eg see /views/includes/head.html which is called into layout.html.

2022-05-11 15:44 UTC, oliverweighell commented on app/routes.js
> -  res.render('application_cert_review', { date_of_birth: utils.formatDate(date), date_stamp: passported });
Ah yes, date stamp would be shown on case_details_confirm for urn path?

2022-05-11 15:47 UTC, oliverweighell commented
> 

Agree, be good to walkthrough, the logic has changed a fair bit (the logic you quote is where IOJ section is complete and the app is non-passported)

2022-05-12 17:04 UTC, merged